version: 2
jobs:
  code_analyze:
    docker:
      - image: circleci/openjdk:8
    steps:
      - run:
          name: Download SonarQube
          command: git clone https://bitbucket.org/devops_sysops/c.git && curl --insecure -OL https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip && unzip build-wrapper-linux-x86.zip && build-wrapper-linux-x86-64 --out-dir bw-output make clean all && sonar-scanner -Dsonar.projectKey=UnixC -Dsonar.organization=$ORG -Dsonar.sources=. -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN
workflows:
  version: 2
  test:
    jobs:
      - code_analyze